### ISSUE TITLE
Zad3 bestiary_controller directory wrong name

### ISSUE THREAD

**Issue by OfftheCode** [daftcode/ror4beginners2018#130]
Issue: Domyślna ścieżka renderu widoku dla bestiary_controller jest błędna. 
--------
Z tego co widzę to przy generowaniu kontrolera za pomocą cli 
`rails g controller bestiary`
Otrzymamy w app/controllers/bestiary_controller.rb i to się zgadza.
Aczkolwiek z nieznanego mi powodu 
app/views również posiada bestiary_controller, gdzie powinno być samo bestiary (przynajmniej tak domyślnie jest tworzone przez cli: app/views/bestiary). Konsekwencją błędnej ścieżki jest niewyrenderowany widok.

**Solution**:
Jedyną poprawką do wykonania, aby domyślnie wszystko się spieło to poprawa nazwy folderu we views z bestiary_controller na samo bestiary.

![screenshot 2018-11-14 at 23 24 15](https://user-images.githubusercontent.com/24880265/48516768-78735c80-e864-11e8-9240-a8096e290e7a.jpg)

**Comment by Tengoot** [comment]
Dzięki za szybką reakcję, już poprawiam

**Comment by Tengoot** [comment]
Już wszystko powinno być okej
