### ISSUE TITLE
instalacja rails pod windows 10

### ISSUE THREAD

**Issue by Kiszuriwalilibori** [daftcode/ror4beginners2018#134]
Mam problem z instalacją ( a właściwie uruchomieniem ) railsów.
Ogólnie dotyczy to problemu z sqlite3.
Przeczytałem ze dwa wątki na stacku, znalazłem coś co miało być pożądanym plikiem sqlite3.h jednak nadal coś jest nie tak, czy ktoś może miał podobny problem?

**Comment by Kombajn27** [comment]
Cześć, też trochę z tym walczyłem (tylko, że na WIN 7, 64-bit). 
To co mi pomogło to: 
ridk exec pacman -S mingw-w64-x86_64-sqlite3
gem inst sqlite3 --platform ruby
gem uninstall sqlite3 --> wybrać trzecią opcję (all)
gem install sqlite3 --platform=ruby

potem rails server powinien już działać (przynajmniej u mnie działa)

Nie pytaj mnie co, jak i dlaczego :) .Spędziłem dużo czasu kombinując, sprawdzając różne rozwiązania. Dlaczego to akurat działa (połączenie dwóch rozwiązań od wujka google) u mnie? Nie mam bladego pojęcia. Mam tylko nadzieję, że Tobie też pomoże. 

Pozdrawiam

**Comment by Kombajn27** [comment]
Niektórzy piszą, że wystarczy wpisać dwie ostatnie komendy, u mnie niestety to nie zadziałało. 
Poniżej linki z których korzystałem przy tym rozwiązaniu, może na coś naprowadzą:
https://github.com/sparklemotion/sqlite3-ruby/issues/228
https://stackoverflow.com/questions/5800920/error-no-such-file-to-load-sqlite3-sqlite3-native-loaderror/6126062#6126062
http://wikiprogramming.org/linux/ruby-2-5-1-windows-fix-cannot-load-such-file-sqlite3-sqlite3_native-loaderror/

**Comment by ahawrylak** [comment]
Niestety Railsy i Windows [nie bardzo ze sobą współpracują](https://github.com/daftcode/ror4beginners2018#windows) - development zawsze odbywa się na Linuxie lub macOS. Ciężko jest powiedzieć mi coś na temat tego konkretnego błędu z sqlite. Moja rada to:
* instalacja linuxa np. Ubuntu(można zainstalować go [obok windowsa na jednej maszynie](https://itsfoss.com/install-ubuntu-1404-dual-boot-mode-windows-8-81-uefi/))
* można też skorzystać z maszyny wirtualnej np [virtualbox](https://www.virtualbox.org/wiki/Downloads)

Można się upierać i nadal próbować pracować z Railsami na Windowsie, jednak prędzej czy później(raczej prędzej) pojawią się kolejne irytujące problemy 😢 🐛

**Comment by Kiszuriwalilibori** [comment]
Dzięki wszystkim. Na razie znalazłem coś o nazwie Instant Rails i dało się to odpalić bez problemu. Tyle, że używa to starej ( 2.33) wersji Ruby'ego, toteż pojawiły się problemy (na szczęście drobne i tutaj podpowiedzi z konsoli stosowały się 1:1, (dodatkowo gdzieś musiałem wpisać wersję Ruby z palca)) z uruchomieniem zadania.
