### ISSUE TITLE
Udostępnianie rozwiązań?

### ISSUE THREAD

**Issue by agnik5** [daftcode/ror4beginners2018#136]
Czy jest szansa na udostępnianie rozwiązań zadań do przeanalizowania na spokojnie bez rozbieganych oczek? :)

**Comment by Tengoot** [comment]
Najpierw napisałem potem sprawdziłem :p Przepraszam, poproszę osobę która je przygotowała o wrzucenie,podejrzewam że powstanie folder rozwiązania.

**Comment by resool** [comment]
rozwiązanie zostało dodane :)
