### ISSUE TITLE
FootballPlayerManager jest niewidoczny

### ISSUE THREAD

**Issue by Kiszuriwalilibori** [daftcode/ror4beginners2018#180]
Przy podaniu w konsoli komendy
`player_manager = FootballPlayerManager.new(player)`
wyskakuje mi błąd :` Unable to autoload constant FootballPlayerManager, expected E:/Rails/Exercise/App/services/football_player_manager.rb to define it.`
Póki co w pliku football_player_manager.rb jest jego oryginalna zawartość a ścieżki są właściwe (nawet jeżeli teraz zrobiłem literówki przepisując je). Ścieżki są takie jakie są, gdyż pliki u mnie są tak właśnie zlokalizowane. Czy to jest jakaś kwestia związana z traktowaniem plików z katalogu services – a jeżeli tak, to gdzie o tym przeczytać, czy chodzi  o coś innego ( a jeżeli tak, gdzie szukać wskazówek)? Zakładam że plik nawet w postaci pierwotnej powinien tworzyć instancję swojej klasy. 'player' jest zdefiniowany i ma wartości.

**Comment by Tengoot** [comment]
Możliwe że projekt w railsach nie ładuje sobie automatycznie tego katalogu :( Na unixowych systemach rails ma automatycznie narzędzie `spring`, które służy właśnie dynamicznemu autoloadowaniu klas w projekcie.

Mógłbyś spróbować w projekcie zamienić zawartość pliku w `config/application.rb` na tą?

```ruby
require_relative 'boot'
require 'rails/all'

Bundler.require(*Rails.groups)

module Zad4
  class Application < Rails::Application
    config.load_defaults 5.2
    config.autoload_paths += %W(#{config.root}/app/services)
  end
end
```

usunąłem komenatarze(z przyzwyczajenia w sumie :D) i dodałem linjkę która może Ci pomóc, mianowicie:

```ruby
config.autoload_paths += %W(#{config.root}/app/services)
```

**Comment by Kiszuriwalilibori** [comment]
Dzięki, zaskoczyło
P.S. czy w opisie zadania nie powinno być `rake db:seed` zamiast `rails db:seed` ?

**Comment by Tengoot** [comment]
Mogło by być, ale w Rails 5 dodano możliwość wywoływania tasków z `rake` przy pomocy komendy `rails` :) `rails` w tym wypadku zachowuje się alias.
